version: "3"
services:
  main:
    image: fenwickelliott/fresh-cookie:root80
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "7000:80"
networks:
  quarknet: